CREATE TABLE IF NOT EXISTS enrollee (id BIGINT(20)  NOT NULL AUTO_INCREMENT, name VARCHAR(150) NOT NULL, activationStatus boolean NOT NULL, birthDate VARCHAR(20) NOT NULL, phoneNumber INT, PRIMARY KEY(id));
CREATE TABLE IF NOT EXISTS dependants(id BIGINT(20)  NOT NULL AUTO_INCREMENT, enrollmentId BIGINT(20) NOT NULL, name VARCHAR(150) NOT NULL, birthDate VARCHAR(20) NOT NULL, PRIMARY KEY(id));
